### ISSUE TITLE
Grabbing MTurk ID

### ISSUE THREAD

**Issue by jzureich** [Nmoleo64/MeliorationWeb#18]
I can setup the interaction with Mechanical Turk so that the MTurk ID is automatically posted to the URL as a querry string ("workerId"). Can we setup the code to grab that parameter as soon as they hit the index page?

**Comment by Nmoleo64** [comment]
Would it be something like this?
`atzweb.x10host.com/index.php?workerId=blah`

**Comment by Nmoleo64** [comment]
I created a new start page that looks nicer and grabs the Worker ID.
