### ISSUE TITLE
Money Machine Error: "508 Resource Limit is Reached" 

### ISSUE THREAD

**Issue by jzureich** [Nmoleo64/MeliorationWeb#20]
This happens occasionally, but I haven't been able to pinpoint any particular reason why it occurs.

![image](https://user-images.githubusercontent.com/30121933/42895054-aac3b072-8a86-11e8-84de-d6fed155f56b.png)

**Comment by Nmoleo64** [comment]
This error means that we have reached the maximum amount of resources allocated to our web server. Our website is only allocated a small percentage of the server's CPU and memory, so this means the limit has been reached. When we switch to AWS or purchase a premium plan at x10 Hosting, this will not happen.
